//! ESP-018.A: `compiler/unicode.argx` is versioned Unicode data, generated
//! here from the standard library the stage0 lexer uses, so the Argorix
//! agent-language lexer classifies characters exactly as stage0 does.
//!
//! - `alphabetic(c)` is `char::is_alphabetic`, the `Alphabetic` property;
//! - `alphanumeric(c)` is `char::is_alphanumeric`: `Alphabetic`, or a
//!   general category of `Nd`, `Nl` or `No`.
//!
//! Each is a tree of comparisons over the property's ranges, so no table is
//! built at run time. The test fails when the file is not what this
//! toolchain's Unicode version gives; `ARGORIX_BLESS=1` rewrites it.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// The ranges of scalar values with the property, merged.
fn ranges(property: impl Fn(char) -> bool) -> Vec<(u32, u32)> {
    let mut found: Vec<(u32, u32)> = Vec::new();
    for value in 0..=0x10_FFFFu32 {
        let Some(character) = char::from_u32(value) else {
            continue;
        };
        if !property(character) {
            continue;
        }
        match found.last_mut() {
            Some((_, end)) if *end + 1 == value => *end = value,
            _ => found.push((value, value)),
        }
    }
    found
}

/// A tree of `if` expressions over `ranges`, sorted and disjoint: a leaf of
/// at most four ranges is their disjunction, an inner node splits at the
/// middle range's start.
fn tree(ranges: &[(u32, u32)], depth: usize, out: &mut String) {
    let indent = "    ".repeat(depth);
    if ranges.len() <= 4 {
        let tests: Vec<String> = ranges
            .iter()
            .map(|(start, end)| {
                if start == end {
                    format!("c == {start}u64")
                } else {
                    format!("(c >= {start}u64 && c <= {end}u64)")
                }
            })
            .collect();
        let _ = writeln!(out, "{indent}{}", tests.join(" || "));
        return;
    }
    let middle = ranges.len() / 2;
    let _ = writeln!(out, "{indent}if c < {}u64 {{", ranges[middle].0);
    tree(&ranges[..middle], depth + 1, out);
    let _ = writeln!(out, "{indent}}} else {{");
    tree(&ranges[middle..], depth + 1, out);
    let _ = writeln!(out, "{indent}}}");
}

fn module() -> String {
    let (major, minor, update) = char::UNICODE_VERSION;
    let mut out = String::new();
    let _ = write!(
        out,
        "core 0.1;
module compiler.unicode;

// Unicode character properties for the agent-language lexer (ESP-018.A),
// Unicode {major}.{minor}.{update}. GENERATED by
// crates/argorixc/tests/unicode_tables.rs from the Rust standard library
// the stage0 lexer uses; regenerate with ARGORIX_BLESS=1, do not edit.
//
// A character is its scalar value. Each property is a tree of comparisons
// over its ranges, so nothing is built at run time.

// `Alphabetic`: what Rust's `char::is_alphabetic` says.
pub fn alphabetic(c: u64) -> bool {{
"
    );
    tree(&ranges(char::is_alphabetic), 1, &mut out);
    out.push_str(
        "}

// `Alphabetic`, or a general category of `Nd`, `Nl` or `No`: what Rust's
// `char::is_alphanumeric` says.
pub fn alphanumeric(c: u64) -> bool {
",
    );
    tree(&ranges(char::is_alphanumeric), 1, &mut out);
    out.push_str("}\n");
    out
}

#[test]
fn the_unicode_module_is_what_the_standard_library_says() {
    let path = root().join("compiler/unicode.argx");
    let expected = module();
    if env::var_os("ARGORIX_BLESS").is_some() {
        fs::write(&path, &expected).unwrap();
    }
    let found = fs::read_to_string(&path).unwrap_or_default();
    assert!(
        found == expected,
        "compiler/unicode.argx is not this toolchain's Unicode {:?}; regenerate it with ARGORIX_BLESS=1",
        char::UNICODE_VERSION
    );
}
