//! Transitional C11 backend for verified Argorix Core IR.
//!
//! ESP-008 owns this Rust stage0 emitter. It intentionally accepts only the
//! proof wrapper created by the Core IR verifier.

use crate::core::{
    CoreIrAssignOp, CoreIrBackend, CoreIrBinaryOp, CoreIrBlock, CoreIrExpr, CoreIrFunction,
    CoreIrItemKind, CoreIrStatement, CoreIrType, CoreIrUnaryOp, VerifiedCoreIr,
};
use std::collections::BTreeMap;
use std::error::Error;
use std::fmt::{self, Write};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CoreCOutput {
    pub source: String,
    pub entry_function: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CoreCError {
    pub code: &'static str,
    pub message: String,
}

impl CoreCError {
    fn unsupported(message: impl Into<String>) -> Self {
        Self {
            code: "CBackendUnsupported",
            message: message.into(),
        }
    }
}

impl fmt::Display for CoreCError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}: {}", self.code, self.message)
    }
}

impl Error for CoreCError {}

#[derive(Debug, Default)]
pub struct CoreCBackend;

impl CoreIrBackend for CoreCBackend {
    type Output = CoreCOutput;
    type Error = CoreCError;

    fn emit(&self, verified: VerifiedCoreIr<'_>) -> Result<Self::Output, Self::Error> {
        Emitter::new(verified).emit()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Signature {
    parameters: Vec<ScalarType>,
    result: ScalarType,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum ScalarType {
    Unit,
    Bool,
    Integer(String),
}

impl ScalarType {
    fn from_ir(value: &CoreIrType) -> Result<Self, CoreCError> {
        let CoreIrType::Named { name } = value else {
            return Err(CoreCError::unsupported(format!(
                "container type `{value:?}` is not lowered by the scalar C profile"
            )));
        };
        match name.as_str() {
            "unit" => Ok(Self::Unit),
            "bool" => Ok(Self::Bool),
            "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => {
                Ok(Self::Integer(name.clone()))
            }
            _ => Err(CoreCError::unsupported(format!(
                "named type `{name}` is not lowered by the scalar C profile"
            ))),
        }
    }

    fn c_name(&self) -> &'static str {
        match self {
            Self::Unit => "void",
            Self::Bool => "bool",
            Self::Integer(name) => match name.as_str() {
                "u8" => "uint8_t",
                "u16" => "uint16_t",
                "u32" => "uint32_t",
                "u64" => "uint64_t",
                "i8" => "int8_t",
                "i16" => "int16_t",
                "i32" => "int32_t",
                "i64" => "int64_t",
                _ => unreachable!("validated scalar integer"),
            },
        }
    }

    fn helper_suffix(&self) -> Result<&str, CoreCError> {
        match self {
            Self::Integer(name) => Ok(name),
            _ => Err(CoreCError::unsupported(
                "checked arithmetic requires an integer",
            )),
        }
    }
}

struct Emitter<'a> {
    verified: VerifiedCoreIr<'a>,
    signatures: BTreeMap<String, Signature>,
}

impl<'a> Emitter<'a> {
    fn new(verified: VerifiedCoreIr<'a>) -> Self {
        Self {
            verified,
            signatures: BTreeMap::new(),
        }
    }

    fn emit(mut self) -> Result<CoreCOutput, CoreCError> {
        let program = self.verified.program();
        for item in &program.items {
            if let CoreIrItemKind::Function(function) = &item.kind {
                let parameters = function
                    .parameters
                    .iter()
                    .map(|parameter| ScalarType::from_ir(&parameter.ty))
                    .collect::<Result<Vec<_>, _>>()?;
                self.signatures.insert(
                    function.name.clone(),
                    Signature {
                        parameters,
                        result: ScalarType::from_ir(&function.return_type)?,
                    },
                );
            } else {
                return Err(CoreCError::unsupported(
                    "the scalar C profile currently accepts function-only modules",
                ));
            }
        }
        let entry = self
            .signatures
            .get("argorix_main")
            .ok_or_else(|| CoreCError::unsupported("module must define `argorix_main`"))?;
        if !entry.parameters.is_empty() || entry.result == ScalarType::Unit {
            return Err(CoreCError::unsupported(
                "`argorix_main` must take no parameters and return a scalar",
            ));
        }

        let mut source = String::new();
        source.push_str(
            "/* generated by Argorix Core C backend 0.1 */\n\
             #include \"argorix_core_runtime.h\"\n\
             #include <inttypes.h>\n\
             #include <stdbool.h>\n\
             #include <stdint.h>\n\
             #include <stdio.h>\n\n",
        );
        for item in &program.items {
            let CoreIrItemKind::Function(function) = &item.kind else {
                unreachable!();
            };
            self.emit_prototype(function, &mut source)?;
        }
        source.push('\n');
        for item in &program.items {
            let CoreIrItemKind::Function(function) = &item.kind else {
                unreachable!();
            };
            FunctionEmitter::new(&self.signatures, function).emit(&mut source)?;
        }
        self.emit_main(entry, &mut source)?;
        Ok(CoreCOutput {
            source,
            entry_function: "argorix_main".into(),
        })
    }

    fn emit_prototype(
        &self,
        function: &CoreIrFunction,
        source: &mut String,
    ) -> Result<(), CoreCError> {
        let signature = &self.signatures[&function.name];
        write!(
            source,
            "static {} argorix_fn_{}(argorix_budget *budget",
            signature.result.c_name(),
            function.name
        )
        .unwrap();
        for (parameter, ty) in function.parameters.iter().zip(&signature.parameters) {
            write!(source, ", {} argorix_v_{}", ty.c_name(), parameter.name).unwrap();
        }
        source.push_str(");\n");
        Ok(())
    }

    fn emit_main(&self, entry: &Signature, source: &mut String) -> Result<(), CoreCError> {
        source.push_str("int main(void) {\n    argorix_budget budget = {1000000U};\n");
        writeln!(
            source,
            "    {} result = argorix_fn_argorix_main(&budget);",
            entry.result.c_name()
        )
        .unwrap();
        match &entry.result {
            ScalarType::Bool => {
                source.push_str(
                    "    (void)printf(\"ARGORIX_RESULT:%s\\n\", result ? \"true\" : \"false\");\n",
                );
            }
            ScalarType::Integer(name) if name.starts_with('u') => {
                source.push_str(
                    "    (void)printf(\"ARGORIX_RESULT:%\" PRIu64 \"\\n\", (uint64_t)result);\n",
                );
            }
            ScalarType::Integer(_) => {
                source.push_str(
                    "    (void)printf(\"ARGORIX_RESULT:%\" PRId64 \"\\n\", (int64_t)result);\n",
                );
            }
            ScalarType::Unit => unreachable!(),
        }
        source.push_str("    return 0;\n}\n");
        Ok(())
    }
}

struct FunctionEmitter<'a> {
    signatures: &'a BTreeMap<String, Signature>,
    function: &'a CoreIrFunction,
    locals: BTreeMap<String, ScalarType>,
    temporary: usize,
}

impl<'a> FunctionEmitter<'a> {
    fn new(signatures: &'a BTreeMap<String, Signature>, function: &'a CoreIrFunction) -> Self {
        let locals = function
            .parameters
            .iter()
            .map(|parameter| {
                (
                    parameter.name.clone(),
                    ScalarType::from_ir(&parameter.ty).expect("signature was validated"),
                )
            })
            .collect();
        Self {
            signatures,
            function,
            locals,
            temporary: 0,
        }
    }

    fn emit(mut self, source: &mut String) -> Result<(), CoreCError> {
        let signature = &self.signatures[&self.function.name];
        write!(
            source,
            "static {} argorix_fn_{}(argorix_budget *budget",
            signature.result.c_name(),
            self.function.name
        )
        .unwrap();
        for (parameter, ty) in self.function.parameters.iter().zip(&signature.parameters) {
            write!(source, ", {} argorix_v_{}", ty.c_name(), parameter.name).unwrap();
        }
        source.push_str(") {\n    argorix_step(budget);\n");
        self.emit_block(&self.function.body, 1, Some(&signature.result), source)?;
        if signature.result == ScalarType::Unit {
            source.push_str("    return;\n");
        }
        source.push_str("}\n\n");
        Ok(())
    }

    fn emit_block(
        &mut self,
        block: &CoreIrBlock,
        indent: usize,
        tail_type: Option<&ScalarType>,
        source: &mut String,
    ) -> Result<(), CoreCError> {
        for statement in &block.statements {
            self.emit_statement(statement, indent, source)?;
        }
        if let Some(tail) = &block.tail {
            let expected = tail_type.ok_or_else(|| {
                CoreCError::unsupported("value block needs an expected scalar type")
            })?;
            let value = self.emit_expr(tail, Some(expected), indent, source)?;
            line(source, indent, &format!("return {};", value.0));
        }
        Ok(())
    }

    fn emit_statement(
        &mut self,
        statement: &CoreIrStatement,
        indent: usize,
        source: &mut String,
    ) -> Result<(), CoreCError> {
        match statement {
            CoreIrStatement::Let {
                name,
                annotation,
                value,
                ..
            } => {
                let declared = annotation.as_ref().map(ScalarType::from_ir).transpose()?;
                let emitted = self.emit_expr(value, declared.as_ref(), indent, source)?;
                let ty = declared.unwrap_or(emitted.1);
                line(
                    source,
                    indent,
                    &format!("{} argorix_v_{} = {};", ty.c_name(), name, emitted.0),
                );
                self.locals.insert(name.clone(), ty);
            }
            CoreIrStatement::Assign {
                target,
                operator,
                value,
            } => {
                let CoreIrExpr::Path { segments } = target else {
                    return Err(CoreCError::unsupported(
                        "scalar C assignment target must be a local path",
                    ));
                };
                let name = single_path(segments)?;
                let ty =
                    self.locals.get(name).cloned().ok_or_else(|| {
                        CoreCError::unsupported(format!("unknown local `{name}`"))
                    })?;
                let right = self.emit_expr(value, Some(&ty), indent, source)?;
                let assignment = match operator {
                    CoreIrAssignOp::Assign => right.0,
                    CoreIrAssignOp::Add
                    | CoreIrAssignOp::Subtract
                    | CoreIrAssignOp::Multiply
                    | CoreIrAssignOp::Divide
                    | CoreIrAssignOp::Remainder => {
                        let operation = assign_operation(*operator);
                        format!(
                            "argorix_{}_{}(argorix_v_{}, {})",
                            ty.helper_suffix()?,
                            operation,
                            name,
                            right.0
                        )
                    }
                };
                line(source, indent, &format!("argorix_v_{name} = {assignment};"));
            }
            CoreIrStatement::While { condition, body } => {
                line(source, indent, "while (true) {");
                line(source, indent + 1, "argorix_step(budget);");
                let condition =
                    self.emit_expr(condition, Some(&ScalarType::Bool), indent + 1, source)?;
                line(
                    source,
                    indent + 1,
                    &format!("if (!{}) {{ break; }}", condition.0),
                );
                self.emit_block(body, indent + 1, None, source)?;
                line(source, indent, "}");
            }
            CoreIrStatement::Return { value } => {
                if let Some(value) = value {
                    let result = &self.signatures[&self.function.name].result;
                    let value = self.emit_expr(value, Some(result), indent, source)?;
                    line(source, indent, &format!("return {};", value.0));
                } else {
                    line(source, indent, "return;");
                }
            }
            CoreIrStatement::Expr { value } => {
                let _ = self.emit_expr(value, None, indent, source)?;
            }
            CoreIrStatement::Break { value: None } => line(source, indent, "break;"),
            CoreIrStatement::Continue => line(source, indent, "continue;"),
            CoreIrStatement::Break { value: Some(_) } => {
                return Err(CoreCError::unsupported(
                    "value breaks are not in scalar C profile",
                ));
            }
        }
        Ok(())
    }

    fn emit_expr(
        &mut self,
        expression: &CoreIrExpr,
        expected: Option<&ScalarType>,
        indent: usize,
        source: &mut String,
    ) -> Result<(String, ScalarType), CoreCError> {
        match expression {
            CoreIrExpr::Integer { value, suffix } => {
                let ty = suffix
                    .as_ref()
                    .map(|name| ScalarType::Integer(name.clone()))
                    .or_else(|| expected.cloned())
                    .ok_or_else(|| CoreCError::unsupported("integer literal needs a type"))?;
                Ok((format!("{value}{}", integer_literal_suffix(&ty)?), ty))
            }
            CoreIrExpr::Bool { value } => Ok((value.to_string(), ScalarType::Bool)),
            CoreIrExpr::Path { segments } => {
                let name = single_path(segments)?;
                let ty = self.locals.get(name).cloned().ok_or_else(|| {
                    CoreCError::unsupported(format!("path `{name}` is not a scalar local"))
                })?;
                Ok((format!("argorix_v_{name}"), ty))
            }
            CoreIrExpr::Unary { operator, value } => {
                let value = self.emit_expr(value, expected, indent, source)?;
                let text = match operator {
                    CoreIrUnaryOp::Not => format!("(!{})", value.0),
                    CoreIrUnaryOp::Negate => {
                        return Err(CoreCError::unsupported(
                            "checked signed negation is not implemented yet",
                        ));
                    }
                };
                self.bind_temp(text, value.1, indent, source)
            }
            CoreIrExpr::Binary {
                left,
                operator,
                right,
            } => self.emit_binary(left, *operator, right, expected, indent, source),
            CoreIrExpr::Call { callee, arguments } => {
                let CoreIrExpr::Path { segments } = callee.as_ref() else {
                    return Err(CoreCError::unsupported(
                        "scalar C profile supports direct function calls only",
                    ));
                };
                let name = single_path(segments)?;
                let signature =
                    self.signatures.get(name).cloned().ok_or_else(|| {
                        CoreCError::unsupported(format!("unknown function `{name}`"))
                    })?;
                let mut emitted = Vec::new();
                for (argument, ty) in arguments.iter().zip(&signature.parameters) {
                    emitted.push(self.emit_expr(argument, Some(ty), indent, source)?.0);
                }
                let call = format!(
                    "argorix_fn_{}(budget{})",
                    name,
                    emitted
                        .iter()
                        .map(|value| format!(", {value}"))
                        .collect::<String>()
                );
                self.bind_temp(call, signature.result, indent, source)
            }
            CoreIrExpr::If {
                condition,
                then_block,
                else_expr,
            } => {
                let ty = expected.cloned().ok_or_else(|| {
                    CoreCError::unsupported("if expression needs an expected scalar type")
                })?;
                let condition =
                    self.emit_expr(condition, Some(&ScalarType::Bool), indent, source)?;
                let temp = self.next_temp();
                line(source, indent, &format!("{} {temp};", ty.c_name()));
                line(source, indent, &format!("if ({}) {{", condition.0));
                self.emit_block_assignment(then_block, &temp, &ty, indent + 1, source)?;
                let else_expr = else_expr
                    .as_ref()
                    .ok_or_else(|| CoreCError::unsupported("value if expression requires else"))?;
                line(source, indent, "} else {");
                let other = self.emit_expr(else_expr, Some(&ty), indent + 1, source)?;
                line(source, indent + 1, &format!("{temp} = {};", other.0));
                line(source, indent, "}");
                Ok((temp, ty))
            }
            CoreIrExpr::Block { body } => {
                let ty = expected.cloned().ok_or_else(|| {
                    CoreCError::unsupported("value block needs an expected scalar type")
                })?;
                let temp = self.next_temp();
                line(source, indent, &format!("{} {temp};", ty.c_name()));
                self.emit_block_assignment(body, &temp, &ty, indent, source)?;
                Ok((temp, ty))
            }
            CoreIrExpr::Unit => Ok(("0".into(), ScalarType::Unit)),
            _ => Err(CoreCError::unsupported(format!(
                "expression `{expression:?}` is outside the scalar C profile"
            ))),
        }
    }

    fn emit_binary(
        &mut self,
        left: &CoreIrExpr,
        operator: CoreIrBinaryOp,
        right: &CoreIrExpr,
        expected: Option<&ScalarType>,
        indent: usize,
        source: &mut String,
    ) -> Result<(String, ScalarType), CoreCError> {
        let left = self.emit_expr(left, expected, indent, source)?;
        if matches!(operator, CoreIrBinaryOp::And | CoreIrBinaryOp::Or) {
            let temp = self.next_temp();
            line(source, indent, &format!("bool {temp} = {};", left.0));
            let condition = if operator == CoreIrBinaryOp::And {
                temp.clone()
            } else {
                format!("!{temp}")
            };
            line(source, indent, &format!("if ({condition}) {{"));
            let right = self.emit_expr(right, Some(&ScalarType::Bool), indent + 1, source)?;
            line(source, indent + 1, &format!("{temp} = {};", right.0));
            line(source, indent, "}");
            return Ok((temp, ScalarType::Bool));
        }
        let right = self.emit_expr(right, Some(&left.1), indent, source)?;
        let (text, result) = match operator {
            CoreIrBinaryOp::Add
            | CoreIrBinaryOp::Subtract
            | CoreIrBinaryOp::Multiply
            | CoreIrBinaryOp::Divide
            | CoreIrBinaryOp::Remainder => (
                format!(
                    "argorix_{}_{}({}, {})",
                    left.1.helper_suffix()?,
                    binary_operation(operator),
                    left.0,
                    right.0
                ),
                left.1,
            ),
            CoreIrBinaryOp::Equal
            | CoreIrBinaryOp::NotEqual
            | CoreIrBinaryOp::Less
            | CoreIrBinaryOp::LessEqual
            | CoreIrBinaryOp::Greater
            | CoreIrBinaryOp::GreaterEqual => (
                format!("({} {} {})", left.0, comparison(operator), right.0),
                ScalarType::Bool,
            ),
            CoreIrBinaryOp::BitOr | CoreIrBinaryOp::BitXor | CoreIrBinaryOp::BitAnd => (
                format!("({} {} {})", left.0, bit_operator(operator), right.0),
                left.1,
            ),
            CoreIrBinaryOp::ShiftLeft | CoreIrBinaryOp::ShiftRight => {
                return Err(CoreCError::unsupported(
                    "checked shifts are not implemented yet",
                ));
            }
            CoreIrBinaryOp::And | CoreIrBinaryOp::Or => unreachable!(),
        };
        self.bind_temp(text, result, indent, source)
    }

    fn emit_block_assignment(
        &mut self,
        block: &CoreIrBlock,
        target: &str,
        ty: &ScalarType,
        indent: usize,
        source: &mut String,
    ) -> Result<(), CoreCError> {
        for statement in &block.statements {
            self.emit_statement(statement, indent, source)?;
        }
        let tail = block
            .tail
            .as_ref()
            .ok_or_else(|| CoreCError::unsupported("value block has no tail expression"))?;
        let value = self.emit_expr(tail, Some(ty), indent, source)?;
        line(source, indent, &format!("{target} = {};", value.0));
        Ok(())
    }

    fn bind_temp(
        &mut self,
        value: String,
        ty: ScalarType,
        indent: usize,
        source: &mut String,
    ) -> Result<(String, ScalarType), CoreCError> {
        if ty == ScalarType::Unit {
            line(source, indent, &format!("{value};"));
            return Ok(("0".into(), ty));
        }
        let temp = self.next_temp();
        line(
            source,
            indent,
            &format!("{} {temp} = {value};", ty.c_name()),
        );
        Ok((temp, ty))
    }

    fn next_temp(&mut self) -> String {
        let value = format!("argorix_t_{}", self.temporary);
        self.temporary += 1;
        value
    }
}

fn line(source: &mut String, indent: usize, value: &str) {
    let _ = writeln!(source, "{}{value}", "    ".repeat(indent));
}

fn single_path(segments: &[String]) -> Result<&str, CoreCError> {
    if let [name] = segments {
        Ok(name)
    } else {
        Err(CoreCError::unsupported(format!(
            "qualified path `{}` is outside the scalar C profile",
            segments.join("::")
        )))
    }
}

fn integer_literal_suffix(ty: &ScalarType) -> Result<&'static str, CoreCError> {
    match ty {
        ScalarType::Integer(name) if name.starts_with('u') => Ok("U"),
        ScalarType::Integer(_) => Ok(""),
        _ => Err(CoreCError::unsupported(
            "integer literal has non-integer type",
        )),
    }
}

fn binary_operation(value: CoreIrBinaryOp) -> &'static str {
    match value {
        CoreIrBinaryOp::Add => "add",
        CoreIrBinaryOp::Subtract => "sub",
        CoreIrBinaryOp::Multiply => "mul",
        CoreIrBinaryOp::Divide => "div",
        CoreIrBinaryOp::Remainder => "rem",
        _ => unreachable!(),
    }
}

fn assign_operation(value: CoreIrAssignOp) -> &'static str {
    match value {
        CoreIrAssignOp::Add => "add",
        CoreIrAssignOp::Subtract => "sub",
        CoreIrAssignOp::Multiply => "mul",
        CoreIrAssignOp::Divide => "div",
        CoreIrAssignOp::Remainder => "rem",
        CoreIrAssignOp::Assign => unreachable!(),
    }
}

fn comparison(value: CoreIrBinaryOp) -> &'static str {
    match value {
        CoreIrBinaryOp::Equal => "==",
        CoreIrBinaryOp::NotEqual => "!=",
        CoreIrBinaryOp::Less => "<",
        CoreIrBinaryOp::LessEqual => "<=",
        CoreIrBinaryOp::Greater => ">",
        CoreIrBinaryOp::GreaterEqual => ">=",
        _ => unreachable!(),
    }
}

fn bit_operator(value: CoreIrBinaryOp) -> &'static str {
    match value {
        CoreIrBinaryOp::BitOr => "|",
        CoreIrBinaryOp::BitXor => "^",
        CoreIrBinaryOp::BitAnd => "&",
        _ => unreachable!(),
    }
}
